version: '3'
services:
  db:
    image: mysql:8
    container_name: crud-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: ./app
    container_name: crud-app
    ports:
      - "5000:5000"
    depends_on:
      - db
